// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNdWbmaVafT62FueXihWMRZwCFT3rJ-4U',
    appId: '1:710543089144:web:b178d358e20ee1e4dc4a0d',
    messagingSenderId: '710543089144',
    projectId: 'boardgamebuddy-v2',
    authDomain: 'boardgamebuddy-v2.firebaseapp.com',
    storageBucket: 'boardgamebuddy-v2.firebasestorage.app',
    measurementId: 'G-6PM8R6Q103',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8SoM8FrJ586rHxwnkS6TiHzrKnVTtXoc',
    appId: '1:710543089144:android:7c7ffb260d08a4eedc4a0d',
    messagingSenderId: '710543089144',
    projectId: 'boardgamebuddy-v2',
    storageBucket: 'boardgamebuddy-v2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSqMeibZDei09jDfr5R1dXkto7b4Hcv6M',
    appId: '1:710543089144:ios:2f78123098cd540fdc4a0d',
    messagingSenderId: '710543089144',
    projectId: 'boardgamebuddy-v2',
    storageBucket: 'boardgamebuddy-v2.firebasestorage.app',
    iosBundleId: 'com.example.boardgame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSqMeibZDei09jDfr5R1dXkto7b4Hcv6M',
    appId: '1:710543089144:ios:2f78123098cd540fdc4a0d',
    messagingSenderId: '710543089144',
    projectId: 'boardgamebuddy-v2',
    storageBucket: 'boardgamebuddy-v2.firebasestorage.app',
    iosBundleId: 'com.example.boardgame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNdWbmaVafT62FueXihWMRZwCFT3rJ-4U',
    appId: '1:710543089144:web:800e7c607fa81e5ddc4a0d',
    messagingSenderId: '710543089144',
    projectId: 'boardgamebuddy-v2',
    authDomain: 'boardgamebuddy-v2.firebaseapp.com',
    storageBucket: 'boardgamebuddy-v2.firebasestorage.app',
    measurementId: 'G-24YME9Q4KY',
  );

}