// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPEViKbMVZ4ICJDb-8GdZO0WYRU_zXc4E',
    appId: '1:527799347898:web:5641b2bab4d7cb5a817083',
    messagingSenderId: '527799347898',
    projectId: 'boardgamebuddy-9ebc3',
    authDomain: 'boardgamebuddy-9ebc3.firebaseapp.com',
    storageBucket: 'boardgamebuddy-9ebc3.firebasestorage.app',
    measurementId: 'G-8Y259MM5EZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmJqiCYFikMwZnYu1lZ8uy5oBzSUowcFI',
    appId: '1:527799347898:android:3277e23591c458c4817083',
    messagingSenderId: '527799347898',
    projectId: 'boardgamebuddy-9ebc3',
    storageBucket: 'boardgamebuddy-9ebc3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIV5eq42mruy9EfPGz62avBJBCMIOflTk',
    appId: '1:527799347898:ios:48d4b851ffcdd747817083',
    messagingSenderId: '527799347898',
    projectId: 'boardgamebuddy-9ebc3',
    storageBucket: 'boardgamebuddy-9ebc3.firebasestorage.app',
    iosBundleId: 'com.example.boardgame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIV5eq42mruy9EfPGz62avBJBCMIOflTk',
    appId: '1:527799347898:ios:48d4b851ffcdd747817083',
    messagingSenderId: '527799347898',
    projectId: 'boardgamebuddy-9ebc3',
    storageBucket: 'boardgamebuddy-9ebc3.firebasestorage.app',
    iosBundleId: 'com.example.boardgame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPEViKbMVZ4ICJDb-8GdZO0WYRU_zXc4E',
    appId: '1:527799347898:web:cb013c005c02221c817083',
    messagingSenderId: '527799347898',
    projectId: 'boardgamebuddy-9ebc3',
    authDomain: 'boardgamebuddy-9ebc3.firebaseapp.com',
    storageBucket: 'boardgamebuddy-9ebc3.firebasestorage.app',
    measurementId: 'G-PNMXVT4TN2',
  );

}